"""two migration

Revision ID: 7bff6abbc063
Revises: 5631c075820b
Create Date: 2025-03-23 10:53:41.764951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bff6abbc063'
down_revision: Union[str, None] = '5631c075820b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_links_custom_alias', 'links', ['custom_alias'], unique=True)
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key('links_user_id_fkey', 'links', 'users', ['user_id'], ['id'])
    op.drop_index('ix_links_custom_alias', table_name='links')
    # ### end Alembic commands ###
